package com.zee.dynamic.excel;

public enum ExcelCellStyleType {
	HEADER_LABEL, HEADER_TYPE, HEADER_FORMAT, HEADER_ID, HEADER_ASSOCIATION, DATA_SUCCESS, DATA_ERROR, DATA_ID, DATA_ASSOCIATION, DATA_READONLY, META, NONE
}
